Add support for multiple communities
Yakimych/relogify-fabulous-app pull request #49
Opened 2020-04-19 08:09 UTC by MargaretKrutikova

This PR fixes #22 by adding ability to have multiple communities with functionality to add and remove communities.

I added `getSelectedCommunity` helper in `AppSettings` that just fetched first community from he list when you need to fetch players and report results, since we haven't implemented tabs yet, but that's a pretty dirty solution for now. Do you have a better suggestion in mind? 😄

2020-04-19 10:45 UTC, Yakimych commented
Looks like there are merge conflicts.

2020-04-19 11:30 UTC, MargaretKrutikova commented
I don't see any conflicts, everything is green here 🟢

2020-04-19 11:57 UTC, Yakimych requested changes
Found some issues after a quick test:
- On first run I end up on the "Players" page with an error message: "Application settings are not set" and a "Try again" button. This should never happen, the "Players"-tab should be invisible (disabled), and we should be on the "Settings" page and forced to add at least one community.
- I should be able to Cancel the dialog if at least one community already exists. Currently there is no "Cancel" button even if I've already added a community previously.

Bonus: might be worth writing a unit test for the second issue before implementing. It should be relatively straightforward with the state-machine-like setup we have.

2020-04-19 11:57 UTC, Yakimych commented on src/Relogify/Relogify.fs
> +
Visual studio is not great at trimming trailing whitespace...

2020-06-19 22:07 UTC, Yakimych commented on src/Relogify/ApplicationSettings.fs
> +let ApplicationSettinsStorageKey = "app_settings_key"
ApplicationSettin**G**sStorageKey

2020-06-20 01:27 UTC, merged

2020-06-20 01:34 UTC, Yakimych commented
@MargaretKrutikova Could you re-open this PR? I pushed a commit from here to master by mistake, and GitHub closed the PR automatically.